WARNING: Logging before InitGoogleLogging() is written to STDERR
I1110 20:56:57.580071 21148 21356 global_state_accessor.cc:25] Redis server address = 10.16.234.175:6379, is test flag = 0
I1110 20:56:57.590077 21148 21356 redis_client.cc:141] RedisClient connected.
I1110 20:56:59.589511 21148 21356 redis_gcs_client.cc:88] RedisGcsClient Connected.
I1110 20:56:59.592512 21148 21356 service_based_gcs_client.cc:75] ServiceBasedGcsClient Connected.
The dashboard on node LAPTOP-JGANR1VS failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda3\envs\RLV\lib\site-packages\ray\dashboard/dashboard.py", line 960, in <module>
    metrics_export_address=metrics_export_address)
  File "C:\anaconda3\envs\RLV\lib\site-packages\ray\dashboard/dashboard.py", line 513, in __init__
    build_dir = setup_static_dir(self.app)
  File "C:\anaconda3\envs\RLV\lib\site-packages\ray\dashboard/dashboard.py", line 414, in setup_static_dir
    "&& npm run build)", build_dir)
FileNotFoundError: [Errno 2] Dashboard build directory not found. If installing from source, please follow the additional steps required to build the dashboard(cd python/ray/dashboard/client && npm ci && npm run build): 'C:\\anaconda3\\envs\\RLV\\lib\\site-packages\\ray\\dashboard\\client/build'

