WARNING: Logging before InitGoogleLogging() is written to STDERR
I1201 21:24:29.295413 34680 52944 global_state_accessor.cc:25] Redis server address = 10.16.199.149:6379, is test flag = 0
I1201 21:24:29.299402 34680 52944 redis_client.cc:141] RedisClient connected.
I1201 21:24:31.288120 34680 52944 redis_gcs_client.cc:88] RedisGcsClient Connected.
I1201 21:24:31.289080 34680 52944 service_based_gcs_client.cc:75] ServiceBasedGcsClient Connected.
The dashboard on node LAPTOP-P22TAOAA failed with the following error:
Traceback (most recent call last):
  File "C:\Users\irohc\anaconda3\envs\drl_proj\lib\site-packages\ray\dashboard/dashboard.py", line 960, in <module>
    metrics_export_address=metrics_export_address)
  File "C:\Users\irohc\anaconda3\envs\drl_proj\lib\site-packages\ray\dashboard/dashboard.py", line 513, in __init__
    build_dir = setup_static_dir(self.app)
  File "C:\Users\irohc\anaconda3\envs\drl_proj\lib\site-packages\ray\dashboard/dashboard.py", line 414, in setup_static_dir
    "&& npm run build)", build_dir)
FileNotFoundError: [Errno 2] Dashboard build directory not found. If installing from source, please follow the additional steps required to build the dashboard(cd python/ray/dashboard/client && npm ci && npm run build): 'C:\\Users\\irohc\\anaconda3\\envs\\drl_proj\\lib\\site-packages\\ray\\dashboard\\client/build'

