WARNING: Logging before InitGoogleLogging() is written to STDERR
I1110 21:28:36.732163 21764 23992 global_state_accessor.cc:25] Redis server address = 10.16.234.175:6379, is test flag = 0
W1110 21:28:36.740170 21764 23992 redis_context.cc:307] Failed to connect to Redis, retrying.
I1110 21:28:36.861970 21764 23992 redis_client.cc:141] RedisClient connected.
I1110 21:28:38.809952 21764 23992 redis_gcs_client.cc:88] RedisGcsClient Connected.
I1110 21:28:38.809952 21764 23992 service_based_gcs_client.cc:75] ServiceBasedGcsClient Connected.
The dashboard on node LAPTOP-JGANR1VS failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda3\envs\RLV\lib\site-packages\ray\dashboard/dashboard.py", line 960, in <module>
    metrics_export_address=metrics_export_address)
  File "C:\anaconda3\envs\RLV\lib\site-packages\ray\dashboard/dashboard.py", line 513, in __init__
    build_dir = setup_static_dir(self.app)
  File "C:\anaconda3\envs\RLV\lib\site-packages\ray\dashboard/dashboard.py", line 414, in setup_static_dir
    "&& npm run build)", build_dir)
FileNotFoundError: [Errno 2] Dashboard build directory not found. If installing from source, please follow the additional steps required to build the dashboard(cd python/ray/dashboard/client && npm ci && npm run build): 'C:\\anaconda3\\envs\\RLV\\lib\\site-packages\\ray\\dashboard\\client/build'

